version: "3.5"

services:
  datastream-relay:
    container_name: datastream-relay
    restart: unless-stopped
    image: datastream-relay
    ports: 
      - 7900:7900
    volumes:
      - /home/dpunisher/repo/zkevm-data-streamer/dist:/app
    command: 
      - "/bin/sh"
      - "-c"
      - "/app/dsrelay"
