
[StreamServer]
Port = 8080
Filename = "streamfile.bin"

[StateDB]
User = "state_user"
Password = "state_password"
Name = "state_db"
Host = "localhost"
Port = "5433"
EnableLog = false	
MaxConns = 200

[Log]
Environment = "development"
Level = "info"
Outputs = ["stdout"]
